import os
#wasa
# --- DIMENSIONES ---
ANCHO_VENTANA = 1080
ALTO_VENTANA = 720

# --- RUTAS ---
CARPETA_IMAGENES = "assets"

# --- COLORES ---
COLOR_FONDO = (74, 67, 95)  # Púrpura pizarra
COLOR_BOTON = (0, 150, 0)
COLOR_BOTON_HOVER = (0, 200, 0)
COLOR_TEXTO = (255, 255, 255)
COLOR_TEXTO_ENTER = (200, 200, 200)

# --- POSICIONES FIJAS ---
CENTRO_PANTALLA = (ANCHO_VENTANA // 2, ALTO_VENTANA // 2)

# Título final
POS_TITULO_FINAL_X = 50
POS_TITULO_FINAL_Y = 50

# Ajustes relativos (Offsets)
AJUSTE_RELOJ_X = 255
AJUSTE_RELOJ_Y = 48
AJUSTE_WAITING_X = 23
AJUSTE_WAITING_Y = 225
AJUSTE_FETCH_X = 45
AJUSTE_FETCH_Y = 236
AJUSTE_EXEC_X = 50
AJUSTE_EXEC_Y = 250

OFFSET_Y_CABLE = 25

# --- VELOCIDADES Y TIEMPOS ---
DISTANCIA_BUS = 210
DURACION_INTRO = 2000     # 2 segundos
VELOCIDAD_DATO = 10
TIEMPO_DATO = DISTANCIA_BUS/(60*VELOCIDAD_DATO) 
# reloj
# ANGULO_FIJO_RELOJ = 45
FRECUENCIA_RELOJ = 2
PERIODO_RELOJ = 1/FRECUENCIA_RELOJ
DISTANCIA_RAM = 190
DISTANCIA_CPU = 261
V_BIT_RELOJ_DERECHA = int(DISTANCIA_RAM/(60*PERIODO_RELOJ/FRECUENCIA_RELOJ))
V_BIT_RELOJ_IZQUIERDA  = int( DISTANCIA_CPU /(60* PERIODO_RELOJ/FRECUENCIA_RELOJ))
