import os
#wasa
# --- DIMENSIONES ---
ANCHO_VENTANA = 1200
ALTO_VENTANA = 720

# --- RUTAS ---
CARPETA_IMAGENES = "assets"

# --- COLORES ---
COLOR_FONDO = (44, 32, 56)  # Cambiado a la ultima version
COLOR_BOTON = (3, 128, 116)
COLOR_BOTON_HOVER = (3, 108, 98)
COLOR_TEXTO = (255, 255, 255)
COLOR_TEXTO_ENTER = (200, 200, 200)

# --- POSICIONES FIJAS ---
CENTRO_PANTALLA = (ANCHO_VENTANA // 2, ALTO_VENTANA // 2)

# Título final
POS_TITULO_FINAL_X = 50
POS_TITULO_FINAL_Y = 50

# Ajustes relativos (Offsets)
AJUSTE_RELOJ_X = 255
AJUSTE_RELOJ_Y = 80
AJUSTE_WAITING_X = 23
AJUSTE_WAITING_Y = 261
AJUSTE_FETCH_X = 45
AJUSTE_FETCH_Y = 272
AJUSTE_EXEC_X = 50
AJUSTE_EXEC_Y = 286

OFFSET_Y_CABLE = 25

# --- VELOCIDADES Y TIEMPOS ---
DISTANCIA_BUS = 210
DURACION_INTRO = 2000     # 2 segundos
VELOCIDAD_DATO = 10
TIEMPO_DATO = DISTANCIA_BUS/(60*VELOCIDAD_DATO) 

## OTROS 
LIMIT_COUNTER = 2  # Aumentar esto para ver el bucle en acción
# reloj
# ANGULO_FIJO_RELOJ = 45
# FRECUENCIA_RELOJ = 2
# PERIODO_RELOJ = 1/FRECUENCIA_RELOJ
# DISTANCIA_RAM = 190
# DISTANCIA_CPU = 261
# V_BIT_RELOJ_DERECHA = int(DISTANCIA_RAM/(60*PERIODO_RELOJ/FRECUENCIA_RELOJ))
# V_BIT_RELOJ_IZQUIERDA  = int( DISTANCIA_CPU /(60* PERIODO_RELOJ/FRECUENCIA_RELOJ))
